config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => '/presign'
  end

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms' => 'static_pages#terms'
  get 'about' => 'static_pages#about'

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations",  unlocks: "users/unlocks"}

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
    get 'sign_in', to: 'users/sessions#new'
    get 'register', to: 'users/registrations#new'
    get 'edit_source', to: 'users/registrations#edit_source', path: 'edit_source'
    patch 'update_source', to: 'users/registrations#update_source', path: 'update_source'
  end

  resources :users, path: '', controller: 'users/users', only: :show do
    resource :payment_settings, controller: 'users/payment_settings', only: [:new, :create, :edit, :update]
    resource :profile, controller: 'users/profiles', only: [:edit, :update]
    resource :location, controller: 'users/locations', only: [:edit, :update]
    resource :theme, controller: 'users/themes', only: [:edit, :update]
    resource :membership, controller: 'users/memberships', only: [:new, :create, :edit, :update, :destroy]
    resources :albums, controller: 'users/albums', except: [:index, :new, :edit] do
      resources :photos, controller: 'users/photos', except: [:index, :new, :edit] do
        resources :votes, controller: 'users/votes', only: [:create, :destroy]
        resources :purchases, path: 'purchases', controller: 'users/purchases', only: [:show, :create, :edit, :update, :destroy] do
          member do
            get 'checkout'
            patch 'charge'
          end
        end
      end
    end
    get 'purchases' => 'users/users#purchases'
    get 'votes' => 'users/users#votes'
    get 'following' => 'users/users#following'
    get 'followers' => 'users/users#followers'
  end

  resources :relationships, controller: 'users/relationships', only: [:create, :update, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    render layout: 'home'
  end
  
  def terms
  end

  def privacy
  end

  def about
  end

end

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>

<div class="full-width-container">
  <div class="container">

    <div class="center-content">
      <div class="three-space medium-text">
        About halowake.com
      </div>

      <div class="mini-title">
        What's the deal with this dumb site?
      </div>

      <div class="three-space">
        Once upon a time, I got bored while at my real job, so I blew it off and created this site for shits and giggles (or "fun" as the locals say.)
      </div>

      <div class="three-space">
        Now, instead of working, you're looking at this site, and you're laughing, and you're enjoying your coffee. Sometimes it squirts out of your nose because you're laughing so hard.
      </div>

      <div class="three-space">
        Go back to looking at the garbage on this site and stop reading this page. Actually, go outside and do something else.
      </div>
    </div>

  </div>
</div>

app/views/static_pages/guidelines.html.erb
<%= provide(:title, "Guidelines") %>

app/views/static_pages/home.html.erb
<div class="back"></div>
<div class="background"></div>

<header class="wrapper">
  <div class="home-header-container">
    <nav class="home-nav">
      <div class="home-site-title">
        <a href="http://halowake.com"><span class="bold">HALO</span>WAKE</a>
      </div>
      <ul>
        <li><%= link_to "Discover", "#", class: "home-nav-links" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Your Page", user_path(current_user), class: "home-nav-links" %></li>
          <li><%= link_to "Sign Out", sign_out_path, class: "home-nav-links" %></li>
        <% else %>
          <li><span class="home-nav-links" id="sign-in">Sign in</span></li>
          <li><span class="home-nav-links" id="register">Register</span></li></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<main class="wrapper ten-space center white">
  <div class="mini-container">
    <div class="large-text">
      Sign up or something
    </div>
    <div class="five-space">
      Here's the reason you should sign up
    </div>
    <div>
      <%= link_to "Sign up", register_path, class: "home-button" %>
    </div>
  </div>
</main>

<% unless user_signed_in? %>

<div id="sign-in-form">
  <div class="profile-form-inside">
    <div class="close"></div>

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :login, "Username or email" %>
        <%= f.text_field :login, autofocus: true, class: "text-field" %>
      </div>

      <div class="field">
        <%= f.label :password %> <%= link_to "I forgot my password.", new_user_password_path, class: "mini-text" %>
        <%= f.password_field :password, autocomplete: "off", class: "text-field" %>
      </div>

      <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>

      <div class="actions border-bottom three-space-bottom-padding">
        <%= f.submit "Log in", class: "submit-button" %>
      </div>
    <% end %>

    <div class="three-space-top">
      <%= link_to "But I don't have an account yet.", register_path %>
    </div>

  </div>
</div>

<div id="register-form">
  <div class="profile-form-inside">
    <div class="close"></div>

    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :username %>
        <%= f.text_field :username, autofocus: true, class: "text-field" %>
      </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, class: "text-field" %>
      </div>

      <div class="field">
        <%= f.label :password %> <span class="dark mini-text">(<%= @minimum_password_length.to_s + " characters minimum." if @minimum_password_length %> Leave blank if you don't want to change it.)</span>
        <%= f.password_field :password, autocomplete: "off", class: "text-field" %>
      </div>

      <div class="actions border-bottom three-space-bottom-padding">
        <%= f.submit "Register", class: "submit-button" %>
      </div>
    <% end %>

    <div class="three-space-top">
      <%= link_to "But I already have an account.", sign_in_path %>
    </div>

  </div>
</div>

<% end %>

app/views/static_pages/privacy.html.erb
<%= provide(:title, "Privacy Policy") %>

app/views/static_pages/terms.html.erb
<%= provide(:title, "Terms of Use") %>