config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => '/presign'
  end

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms' => 'static_pages#terms'
  get 'about' => 'static_pages#about'

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations",  unlocks: "users/unlocks"}

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
    get 'sign_in', to: 'users/sessions#new'
    get 'register', to: 'users/registrations#new'
    get 'edit_source', to: 'users/registrations#edit_source', path: 'edit_source'
    patch 'update_source', to: 'users/registrations#update_source', path: 'update_source'
  end

  resources :users, path: '', controller: 'users/users', only: :show do
    resource :payment_settings, controller: 'users/payment_settings', only: [:new, :create, :edit, :update]
    resource :profile, controller: 'users/profiles', only: [:edit, :update]
    resource :location, controller: 'users/locations', only: [:edit, :update]
    resource :theme, controller: 'users/themes', only: [:edit, :update]
    resource :membership, controller: 'users/memberships', only: [:new, :create, :edit, :update, :destroy]
    resources :albums, controller: 'users/albums', except: [:index, :new, :edit] do
      resources :photos, controller: 'users/photos', except: [:index, :new, :edit] do
        resources :votes, controller: 'users/votes', only: [:create, :destroy]
        resources :purchases, path: 'purchases', controller: 'users/purchases', only: [:show, :create, :edit, :update, :destroy] do
          member do
            get 'checkout'
            patch 'charge'
          end
        end
      end
    end
    get 'purchases' => 'users/users#purchases'
    get 'votes' => 'users/users#votes'
    get 'following' => 'users/users#following'
    get 'followers' => 'users/users#followers'
  end

  resources :relationships, controller: 'users/relationships', only: [:create, :update, :destroy]

end

app/models/photo.rb
class Photo < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  include ImageUploader[:image]

  enum photo_type: [:photo, :art]
  enum transport_type: [:downloadable, :shippable]

  default_scope -> { order('id DESC') }

  belongs_to :album
  belongs_to :user

  has_many :votes, dependent: :destroy
  has_many :purchases

  validates :user_id, presence: true
  validates :image_data, presence: true, unless: :image_data?
  validates :photo_type, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 3000 }, allow_blank: true

  #validates :resolution, allow_blank: true
  validates :camera, length: { maximum: 255 }, allow_blank: true
  validates :lens, length: { maximum: 255 }, allow_blank: true
  validates :aperture, length: { maximum: 4 }, format: { with: /[0-9]{1,2}[.][0-9]{1}/ }, allow_blank: true
  validates :exposure, length: { maximum: 6 }, format: { with: /\A[-1-9]+[0-9]{0,}?([\/][-1-9])?+[0-9]{0,}?\z/ }, allow_blank: true
  #validates :flash, allow_blank: true
  validates :focal_length, length: { maximum: 6 }, format: { with: /[0-9]{1,4}[.][0-9]{1}/ }, allow_blank: true
  validates :iso, length: { maximum: 5 }, format: { with: /[1-9]{1}[0-9]{2,4}/ }, allow_blank: true
  validates :tool, length: { maximum: 255 }, allow_blank: true
  validates :medium, length: { maximum: 255 }, allow_blank: true
  validates :surface, length: { maximum: 255 }, allow_blank: true
  validates :size, length: { maximum: 255 }, allow_blank: true
  validates :style, length: { maximum: 255 }, allow_blank: true

  validates :currency, presence: true, if: :is_for_sale
  validates :base_price, presence: true, length: { maximum: 6 }, numericality: { greater_than: 0}, if: :is_for_sale
  validates :shipping_price, presence: true, length: { maximum: 6 }, numericality: { greater_than: -1}, if: :is_for_sale && :shippable?
  validates :quantity, presence: true, if: :is_for_sale
  #validates :total_price, presence: true, if: :is_for_sale
  
  before_save :no_shipping
  before_save :reset_photo_options
  before_save :reset_art_options
  before_save :reset_sales_options
  before_save :total_price_calculator
  before_save :should_generate_new_friendly_id?, if: :title_changed?

  def photo_resolution
   # get photo resolution from metadata
  end

  private

    def is_for_sale
      self.for_sale == true
    end

    def no_shipping
      self.shipping_price = 0 if self.downloadable?
    end

    def reset_sales_options
      if self.for_sale == false
        self.base_price = nil
        self.shipping_price = nil
        self.currency = nil
        self.quantity = nil
        self.total_price = nil
      end
    end

    def reset_photo_options
      if self.art?
        self.resolution = nil
        self.camera = nil
        self.lens = nil
        self.aperture = nil
        self.exposure = nil
        self.flash = nil
        self.focal_length = nil
        self.iso = nil
      end
    end

    def reset_art_options
      if self.photo?
        self.tool = nil
        self.medium = nil
        self.surface = nil
        self.size = nil
        self.style = nil
      end
    end

    def total_price_calculator
      self.total_price = base_price + shipping_price if self.for_sale?
    end

    def should_generate_new_friendly_id?
      title_changed?
    end

end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController

  before_action :authenticate_user!, except: :show
  before_action :correct_user, only: :create
  before_action :correct_photo_user, only: :destroy
  before_action :set_user, except: :show

  def show
    @user = User.friendly.find(params[:user_id])
    @album = Album.friendly.find(params[:album_id])
    @photo = Photo.friendly.find(params[:id])

    if user_signed_in?
      Stripe.api_key = "sk_test_ECd3gjeIEDsGkySmF8FQOC5i"
      @customer = Stripe::Customer.retrieve(current_user.customer_id)
    end
  end

  def create
    @album = Album.friendly.find(params[:album_id])
    @photo = @album.photos.build(photo_params)
    @photo.user_id = @user.id
    if @result = @photo.save
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:notice] = "You've successfully added a photo!"
      end
    else
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:alert] = "You've failed to add a photo!"
      end
    end
  end

  def update
    @album = Album.friendly.find(params[:album_id])
    @photo = Photo.friendly.find(params[:id])
    if @result = @photo.update_attributes(photo_params)
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:notice] = "You've successfully updated your photo!"
      end
    else
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:alert] = "You've failed to update this photo!"
      end
    end
  end

  def destroy
    @album = Album.friendly.find(params[:album_id])
    Photo.friendly.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_album_path(@user, @album) }
      format.js { render :action => "photos" }
      flash.now[:notice] = "You've successfully deleted your photo!"
    end
  end

  private

    def set_user
      @user = current_user
    end

    def correct_user
      @user = User.friendly.find(params[:user_id])
      if current_user != @user
        redirect_to user_path(@user)
        flash[:alert] = "This is not your profile."
      end
    end

    def correct_photo_user
      @photo = Photo.friendly.find(params[:id])
      redirect_to user_path(@photo.user_id) if @photo.user_id != current_user.id
    end

    def photo_params
      params.require(:photo).permit(:title, :image, :remove_image, :description, :resolution, :camera, :lens, :aperture, :exposure, :flash, :focal_length, :iso, :for_sale, :base_price, :shipping_price, :total_price, :currency, :quantity, :photo_type, :tool, :medium, :surface, :size, :style, :transport_type)
    end

end

app/views/users/partials/photos/_photo_details.html.erb
<% if @photo.for_sale == true %>
  <div class="nameplate border-bottom">
    <div class="first-column">
      <div id="purchase-photo" class="submit-button">
        Purchase
      </div>
    </div>
    <div class="second-column">
      <% if @photo.base_price.present? %>
        <div class="one-sixth">
          <div class="bold">
            Base Price:
          </div>
          <div class="one-space-left">
            <%= @photo.base_price %> <%= @photo.currency %>
          </div>
        </div>
      <% end %>
      <% if @photo.shippable? %>
        <div class="one-sixth">
          <div class="bold">
            Shipping Price:
          </div>
          <div class="one-space-left">
            <%= @photo.shipping_price %> <%= @photo.currency %>
          </div>
        </div>
      <% end %>
      <% if @photo.total_price.present? %>
        <div class="one-sixth">
          <div class="bold">
            Total Price:
          </div>
          <div class="one-space-left">
            <%= @photo.total_price %> <%= @photo.currency %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% if @photo.photo? && (@photo.camera.present? || @photo.lens.present? || @photo.aperture.present? || @photo.exposure.present? || @photo.flash.present? || @photo.focal_length.present? || @photo.iso.present?) %>
  <div class="nameplate border-bottom">
    <% if @photo.camera.present? %>
      <div class="one-space-bottom medium-text">
        <%= link_to @photo.camera, "https://www.amazon.com/s/ref=as_li_ss_tl?url=search-alias=aps&field-keywords=#{@photo.camera}&linkCode=ll2&tag=letlyrics08-20&linkId=293aefe04a0280e01bef782242640c24", target: :_blank  %>
      </div>
    <% end %>
    <% if @photo.lens.present? %>
      <div class="one-sixth">
        <div class="bold">
          Lens:
        </div>
        <div class="one-space-left">
          <%= @photo.lens %>
        </div>
      </div>
    <% end %>
    <% if @photo.aperture.present? %>
      <div class="one-sixth">
        <div class="bold">
          Aperture:
        </div>
        <div class="one-space-left">
          ƒ/<%= @photo.aperture %>
        </div>
      </div>
    <% end %>
    <% if @photo.exposure.present? %>
      <div class="one-sixth">
        <div class="bold">
          Exposure:
        </div>
        <div class="one-space-left">
          <%= @photo.exposure %>s
        </div>
      </div>
    <% end %>
    <% if @photo.flash.present? %>
      <div class="one-sixth">  
        <div class="bold">
          Flash:
        </div>
        <div class="one-space-left">
          <%= @photo.flash %>
        </div>
      </div>
    <% end %>
    <% if @photo.focal_length.present? %>
      <div class="one-sixth"> 
        <div class="bold">
          Focal length:
        </div>
        <div class="one-space-left">
          <%= @photo.focal_length %>mm
        </div>
      </div>
    <% end %>
    <% if @photo.iso.present? %>
      <div class="one-sixth">
        <div class="bold">
          ISO:
        </div>
        <div class="one-space-left">
          <%= @photo.iso %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @photo.art? && (@photo.tool.present? || @photo.medium.present? || @photo.surface.present? || @photo.size.present? || @photo.style.present?) %>
  <div class="nameplate border-bottom">
    <% if @photo.tool.present? %>
      <div class="one-sixth">
        <div>
          Tool:
        </div>
        <%= @photo.tool %>
      </div>
    <% end %>
    <% if @photo.medium.present? %>
      <div class="one-sixth">
        <div>
          Medium:
        </div>
        <%= @photo.medium %>
      </div>
    <% end %>
    <% if @photo.surface.present? %>
      <div class="one-sixth">
        <div>
          Surface:
        </div>
        <%= @photo.surface %>
      </div>
    <% end %>
    <% if @photo.style.present? %>
      <div class="one-sixth">  
        <div>
          Style:
        </div>
        <%= @photo.style %>
      </div>
    <% end %>
    <% if @photo.size.present? %>
      <div class="one-sixth"> 
        <div>
          Size:
        </div>
        <%= @photo.size %>
      </div>
    <% end %>
  </div>
<% end %>

<% if @photo.description.present? %>
  <div class="nameplate border-bottom">
    <%= sanitize(@photo.description) %>
  </div>
<% end %>

app/views/users/partials/photos/_photo_form.html.erb
<div id="album-form">
  <div class="profile-form-inside">
    <div class="close"></div>

    <%= form_for(@photo, url: user_album_photos_path(@user, @album), remote: true) do |f| %>
      <span id="photo_errors"><%= render 'partials/errors/photo_errors' %></span>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: "text-field" %>
      </div>
      <div class="field">
        <%= f.label :image %>
        <%= f.hidden_field :image, value: Photo.new.cached_image_data %>
        <%= f.file_field :image %>
      </div>

      <div class="field flex">
        <label class="checked-tab" id="photo-tab" for="is-photo-click">Photo</label>
        <%= f.radio_button(:photo_type, "photo", id: "is-photo-click", checked: true) %>

        <label class="unchecked-tab" id="art-tab" for="is-art-click">Art</label>
        <%= f.radio_button(:photo_type, "art", id: "is-art-click") %>
      </div>

      <div id="optional-fields-click" class="field-padding border-top">
        Options &#9660;
      </div>
      <div id="optional-fields-close">
        <div class="field-padding border-top">
          Options &#9650;
        </div>
      </div>

      <div id="optional-fields">
        <div id="photo-fields" class="three-space-top-padding border-top">
          <div class="field">
            <%= f.label :resolution %>
            <%= f.text_field :resolution, class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :camera %>
            <%= f.text_field :camera, placeholder: "Example: Canon EOS 5D Mark III", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :lens %>
            <%= f.text_field :lens, placeholder: "Example: EF24-105mm f/4L IS USM", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :aperture %> <span class="dark mini-text">(ƒ/)</span>
            <%= f.text_field :aperture, placeholder: "Example: 7.1", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :exposure %> <span class="dark mini-text">(in seconds)</span>
            <%= f.text_field :exposure, placeholder: "Example: 1/100 or 30", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :flash %>
            <%= f.text_field :flash, class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :focal_length %> <span class="dark mini-text">(in millimeters)</span>
            <%= f.text_field :focal_length, placeholder: "Example: 28.0", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :iso, "ISO" %>
            <%= f.text_field :iso, placeholder: "Example: 250", class: "text-field" %>
          </div>
        </div>

        <div id="art-fields" class="three-space-top-padding border-top">
          <div class="field">
            <%= f.label :tool %>
            <%= f.text_field :tool, placeholder: "Example: Brush", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :medium %>
            <%= f.text_field :medium, placeholder: "Example: Paint", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :surface %>
            <%= f.text_field :surface, placeholder: "Example: Canvas", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :style %>
              <%= f.text_field :style, placeholder: "Example: Abstract", class: "text-field" %>
          </div>
          <div class="field">
            <%= f.label :size %> (in inches)
            <%= f.text_field :size, placeholder: "Example: 24x36", class: "text-field" %>
          </div>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, class: "text-area" %>
        </div>

        <% if current_user.payment_setting.present? && current_user.payment_setting.stripe_id.present? %>
          <div class="field">
            <%= f.label :for_sale %>
            <%= f.check_box :for_sale, class: "text-field", id: "for-sale" %>
          </div>
          <div id="for-sale-container">
            <div class="field">
              <%= f.label :base_price %>
              <%= f.text_field :base_price, class: "text-field" %>
            </div>

            <div class="field flex">
              <label class="checked-tab" id="downloadable-tab" for="downloadable">Downloadable</label>
              <%= f.radio_button(:transport_type, "downloadable", id: "downloadable", checked: true) %>

              <label class="unchecked-tab" id="shippable-tab" for="shippable">Shippable</label>
              <%= f.radio_button(:transport_type, "shippable", id: "shippable") %>
            </div>

            
            <div id="shippable-fields">
              <div class="field">
                <%= f.label :shipping_price %>
                <%= f.text_field :shipping_price, class: "text-field" %>
              </div>
            </div>
            <div class="field">
              <%= f.label :currency %>
              <%= f.text_field :currency, class: "text-field" %>
            </div>
            <div class="field">
              <%= f.label :quantity %>
              <%= f.text_field :quantity, class: "text-field" %>
            </div>
          </div>
        <% end %>
      </div>

      <%= f.submit "Create photo", data: { disable_with: 'Creating...' }, class: "submit-button" %>
    <% end %>

  </div>
</div>

app/views/users/partials/photos/_photo_purchase_form.html.erb
<% if @photo.for_sale? %>

  <div id="purchase-form">
    <div class="profile-form-inside">
      <div class="close"></div>
      <div class="medium-text one-space">
        <%= @photo.title %>
      </div>
      <div class="one-space">
        <%= @photo.total_price %> <%= @photo.currency %>
      </div>
      <%= form_for(Purchase.new, url: user_album_photo_purchases_path(@user, @album, @photo)) do |f| %>
        <%= render 'partials/errors/photo_errors' %>
        <div class="field">
          <div class="one-thirds">
            <%= f.label :quantity %>
          </div>
          <div class="two-thirds">
            <%= f.text_field :quantity, class: "text-field" %>
          </div>
        </div>
        <div class="field">
          <div class="one-thirds">
            <%= f.label :pay_your_own_price %>
          </div>
          <div class="two-thirds">
            <%= f.text_field :pay_your_own_price, class: "text-field" %>
          </div>
          <div class="one-space">
            Put extra money in your artist's pocket. The Stripe fee for this transaction will be $<%= (@photo.total_price * 0.04 + 0.30).ceil %>.
          </div>
        </div>
        <%= f.submit "Purchase", data: { disable_with: 'Loading...' }, class: "submit-button" %>
      <% end %>
      <% if @customer.default_source.present? %>
        <div class="one-space">
          You have a card on file. Pressing "Purchase" will automatically finish this process, including charging your card. If you'd like to change your card, <%= link_to "please do so before continuing", edit_source_path(current_user) %>.
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/users/partials/photos/_photo_title.html.erb
 <%= @photo.title %>