config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => '/presign'
  end

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms' => 'static_pages#terms'
  get 'about' => 'static_pages#about'

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations",  unlocks: "users/unlocks"}

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
    get 'sign_in', to: 'users/sessions#new'
    get 'register', to: 'users/registrations#new'
    get 'edit_source', to: 'users/registrations#edit_source', path: 'edit_source'
    patch 'update_source', to: 'users/registrations#update_source', path: 'update_source'
  end

  resources :users, path: '', controller: 'users/users', only: :show do
    resource :payment_settings, controller: 'users/payment_settings', only: [:new, :create, :edit, :update]
    resource :profile, controller: 'users/profiles', only: [:edit, :update]
    resource :location, controller: 'users/locations', only: [:edit, :update]
    resource :theme, controller: 'users/themes', only: [:edit, :update]
    resource :membership, controller: 'users/memberships', only: [:new, :create, :edit, :update, :destroy]
    resources :albums, controller: 'users/albums', except: [:index, :new, :edit] do
      resources :photos, controller: 'users/photos', except: [:index, :new, :edit] do
        resources :votes, controller: 'users/votes', only: [:create, :destroy]
        resources :purchases, path: 'purchases', controller: 'users/purchases', only: [:show, :create, :edit, :update, :destroy] do
          member do
            get 'checkout'
            patch 'charge'
          end
        end
      end
    end
    get 'purchases' => 'users/users#purchases'
    get 'votes' => 'users/users#votes'
    get 'following' => 'users/users#following'
    get 'followers' => 'users/users#followers'
  end

  resources :relationships, controller: 'users/relationships', only: [:create, :update, :destroy]

end

app/controllers/users/albums_controller.rb
class Users::AlbumsController < ApplicationController

  before_action :authenticate_user!, except: :show
  before_action :correct_user, only: :create
  before_action :correct_album_user, only: :destroy
  before_action :set_user, except: :show

  def show
    @user = User.friendly.find(params[:user_id])
    @album = Album.friendly.find(params[:id])
    if user_signed_in? && current_user == @user
      @profile = current_user.profile
      @location = current_user.location
      @theme = current_user.theme
      @photo = Photo.new
    end
  end

  def create
    @album = @user.albums.build(album_params)
    if @result = @album.save
      respond_to do |format|
        format.html { redirect_to (:back) }
        format.js { render :action => "albums" }
        flash.now[:notice] = "You've successfully added a photo album!"
      end
    else
      respond_to do |format|
        format.html { redirect_to (:back) }
        format.js { render :action => "albums" }
        flash.now[:alert] = "You've failed!"
      end
    end
  end

  def update
    @album = Album.friendly.find(params[:id])
    if @result = @album.update_attributes(album_params)
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js { render :action => "albums" }
        flash.now[:notice] = "You've successfully updated your photo album!"
      end
    else
      respond_to do |format|
        format.html { redirect_to (:back) }
        format.js { render :action => "albums" }
        flash.now[:alert] = "You've failed!"
      end
    end
  end

  def destroy
    Album.friendly.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to (:back) }
      format.js { render :action => "albums" }
      flash.now[:notice] = "You've successfully deleted a photo album!"
    end
  end

  private

    def set_user
      @user = current_user
    end

    def correct_user
      @user = User.friendly.find(params[:user_id])
      if current_user != @user
        redirect_to user_path(@user)
        flash[:alert] = "This is not your profile."
      end
    end

    def correct_album_user
      @album = Album.friendly.find(params[:id])
      redirect_to user_path(@album.user_id) if @album.user_id != current_user.id
    end

    def album_params
      params.require(:album).permit(:title, :description)
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/locations_controller.rb
class Users::LocationsController < ApplicationController

end

app/controllers/users/memberships_controller.rb
class Users::MembershipsController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_user

  def edit
    @membership = @user.membership
  end

  def update
    @membership = @user.membership

    # update current_id to match plan id
    @membership.update_attributes(
      current_id: params[:membership][:membership_type] + "_id"
    )
   
    Stripe.api_key = "sk_test_ECd3gjeIEDsGkySmF8FQOC5i"

    # find customer
    customer = Stripe::Customer.retrieve(@user.customer_id)
    
    # check if customer has a source on file
    if customer.default_source.blank?
      url = "#{request.protocol}#{request.host_with_port}#{request.fullpath}/edit"
      redirect_to edit_source_path(@user, :url => Base64.encode64(url))
    else
      # if user has subscription find it if not create i
      if @membership.membership_id.blank?
        # create a Stripe membership
        subscription = Stripe::Subscription.create({
        customer: customer.id,
          items: [{plan: @membership.current_id}],
        })
      else
        # grab Stripe membership and update it
        subscription = Stripe::Subscription.retrieve(@membership.membership_id)
        subscription.items = [{
          id: subscription.items.data[0].id,
          plan: @membership.current_id
        }]
      end

      subscription.save

      if subscription.save
        @membership.update_attributes(
          membership_id: subscription.id,
          membership_type: params[:membership][:membership_type]
        )
        redirect_to user_path(@user)
      end
    end

  end

  private

    def set_user
      @user = current_user
    end

    def correct_user
      @user = User.friendly.find(params[:user_id])
      if current_user != @user
        redirect_to user_path(@user)
        flash[:alert] = "This is not your profile."
      end
    end

    def membership_params
      params.require(:membership).permit(:membership_id, :current_id, :membership_type, :percent)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/payment_settings_controller.rb
class Users::PaymentSettingsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_user
  before_action :have_merchant_account, only: [:new, :create]

  def new
    @payment = PaymentSetting.new
  end

  def create

    Stripe.api_key = "sk_test_ECd3gjeIEDsGkySmF8FQOC5i"

    @account = Stripe::Account.create(
      type: 'custom',
      country: params[:payment_setting][:country],
      email: @user.email,
      tos_acceptance: {
        ip: request.remote_ip,
        date: Time.now.to_i
      },
      legal_entity: {
        dob: {
          month: params[:payment_setting][:month],
          day: params[:payment_setting][:day],
          year: params[:payment_setting][:year]
        },
        first_name: params[:payment_setting][:first_name],
        last_name: params[:payment_setting][:last_name],
        type: 'individual'
      }
    )

    if @account.save
      @payment = @user.create_payment_setting(
        first_name: @account.legal_entity.first_name,
        last_name: @account.legal_entity.last_name,
        month: @account.legal_entity.dob.month,
        day: @account.legal_entity.dob.day,
        year: @account.legal_entity.dob.year,
        currency: @account.default_currency,
        country: @account.country,
        stripe_id: @account.id
      )
      redirect_to edit_user_payment_settings_path(@user, @payment)
      flash[:notice] = "Before we can transfer your payments we need more information."
    else
      redirect_to user_path(@user)
      flash[:alert] = "Your merchant account failed to create."
    end

  end

  def edit
    @payment = @user.payment_setting
  end

  def update
    @payment = @user.payment_setting

    Stripe.api_key = "sk_test_ECd3gjeIEDsGkySmF8FQOC5i"

    account = Stripe::Account.retrieve(@payment.stripe_id)

    if params[:payment_setting][:bank_account_number].present?
      account.external_accounts.create(
        external_account: {
          object: 'bank_account',
          account_number: params[:payment_setting][:bank_account_number],
          routing_number: params[:payment_setting][:bank_routing_number],
          country: account.country,
          currency: params[:payment_setting][:currency]
        }
      )
    end

    account.legal_entity.address.line1 = params[:payment_setting][:line1]
    account.legal_entity.address.city = params[:payment_setting][:city]
    account.legal_entity.address.postal_code = params[:payment_setting][:postal_code]
    account.legal_entity.personal_address.line1 = params[:payment_setting][:line1] unless account.country == 'US'
    account.legal_entity.personal_address.city = params[:payment_setting][:city] unless account.country == 'US'
    account.legal_entity.personal_address.postal_code = params[:payment_setting][:postal_code] unless account.country == 'US'
    account.legal_entity.address.state = params[:payment_setting][:state]
    account.legal_entity.ssn_last_4 = params[:payment_setting][:ssn_last_4] if params[:payment_setting][:ssn_last_4]
    account.legal_entity.personal_id_number = params[:payment_setting][:personal_id_number] if params[:payment_setting][:personal_id_number]
    account.default_currency = params[:payment_setting][:currency]

    account.save

    if account.save
      @payment.update_attributes(
        first_name: params[:payment_setting][:first_name],
        last_name: params[:payment_setting][:last_name],
        month: params[:payment_setting][:month],
        day: params[:payment_setting][:day],
        year: params[:payment_setting][:year],
        currency: account.default_currency
      )
      if @payment.save
      redirect_to user_path(@user)
      flash[:notice] = "you've updated your merchant account."
      else
        render 'edit'
      end
    else
      redirect_to user_path(@user)
      flash[:alert] = "your merchant account failed to update."
    end

  end

  private

    def set_user
      @user = current_user
    end

    def correct_user
      @user = User.friendly.find(params[:user_id])
      if current_user != @user
        redirect_to user_path(@user)
        flash[:alert] = "this is not you."
      end
    end

    def have_merchant_account
      @user = current_user
      if @user.payment_setting
        @payment = @user.payment_setting
        redirect_to edit_user_payment_settings_path(@user, @payment) if @payment.country.present?
      end
    end

end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController

  before_action :authenticate_user!, except: :show
  before_action :correct_user, only: :create
  before_action :correct_photo_user, only: :destroy
  before_action :set_user, except: :show

  def show
    @user = User.friendly.find(params[:user_id])
    @album = Album.friendly.find(params[:album_id])
    @photo = Photo.friendly.find(params[:id])

    if user_signed_in?
      Stripe.api_key = "sk_test_ECd3gjeIEDsGkySmF8FQOC5i"
      @customer = Stripe::Customer.retrieve(current_user.customer_id)
    end
  end

  def create
    @album = Album.friendly.find(params[:album_id])
    @photo = @album.photos.build(photo_params)
    @photo.user_id = @user.id
    if @result = @photo.save
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:notice] = "You've successfully added a photo!"
      end
    else
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:alert] = "You've failed to add a photo!"
      end
    end
  end

  def update
    @album = Album.friendly.find(params[:album_id])
    @photo = Photo.friendly.find(params[:id])
    if @result = @photo.update_attributes(photo_params)
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:notice] = "You've successfully updated your photo!"
      end
    else
      respond_to do |format|
        format.html { redirect_to user_album_path(@user, @album) }
        format.js { render :action => "photos" }
        flash.now[:alert] = "You've failed to update this photo!"
      end
    end
  end

  def destroy
    @album = Album.friendly.find(params[:album_id])
    Photo.friendly.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_album_path(@user, @album) }
      format.js { render :action => "photos" }
      flash.now[:notice] = "You've successfully deleted your photo!"
    end
  end

  private

    def set_user
      @user = current_user
    end

    def correct_user
      @user = User.friendly.find(params[:user_id])
      if current_user != @user
        redirect_to user_path(@user)
        flash[:alert] = "This is not your profile."
      end
    end

    def correct_photo_user
      @photo = Photo.friendly.find(params[:id])
      redirect_to user_path(@photo.user_id) if @photo.user_id != current_user.id
    end

    def photo_params
      params.require(:photo).permit(:title, :image, :remove_image, :description, :resolution, :camera, :lens, :aperture, :exposure, :flash, :focal_length, :iso, :for_sale, :base_price, :shipping_price, :total_price, :currency, :quantity, :photo_type, :tool, :medium, :surface, :size, :style, :transport_type)
    end

end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  
  def create
    user = User.find(params[:followed_id])
    @user = User.friendly.find(user)
    current_user.follow(user)
    respond_to do |format|
      format.html { redirect_to (:back) }
      format.js { render :action => "relationships" }
      flash.now[:notice] = "You have successfully followed #{@user.profile.first_name.presence || @user.username}."
    end
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    @user = User.friendly.find(user)
    current_user.unfollow(user)
    respond_to do |format|
      format.html { redirect_to (:back) }
      format.js { render :action => "relationships" }
      flash.now[:notice] = "You have successfully unfollowed #{@user.profile.first_name.presence || @user.username}."
    end
  end
  
end

app/controllers/users/themes_controller.rb
class Users::ThemesController < ApplicationController

end

app/helpers/payment_settings_helper.rb
module PaymentSettingsHelper

  def country_select
    [
      ['US'],
      ['AT'],
      ['AU'],
      ['BE'],
      ['CA'],
      ['DE'],
      ['DK'],
      ['ES'],
      ['FI'],
      ['FR'],
      ['GB'],
      ['IE'],
      ['IT'],
      ['JP'],
      ['LU'],
      ['NL'],
      ['NO'],
      ['SE']
    ]
  end

  def default_currency
    [
      ['USD'],
      ['AUD'],
      ['CAD'],
      ['CHF'],
      ['DKK'],
      ['EUR'],
      ['GBP'],
      ['JPY'],
      ['MXN'],
      ['NOK'],
      ['SEK'],
      ['SGD']
    ]
  end

end

app/views/users/payment_settings/edit.html.erb
<%= provide(:title, "Set Up A Merchant Account, Part 2" + " | " + "Halowake") %>

<div class="wrapper">
  <div class="container">

    <div class="three-space medium-text">
      Set up a merchant account, part 2
    </div>

    <div class="nameplate border-top">
      <div class="form-container">
        <%= form_for(@payment, url: user_payment_settings_path) do |f| %>
          <%= f.hidden_field :user_id %>
          <%= render 'partials/errors/payment_setting_errors' %>       
            <div class="flex">
              <div class="one-half-form">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: "text-field" %>
              </div>
              <div class="one-half-form">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: "text-field" %>
              </div>
            </div>
            <div class="flex">
              <div class="one-thirds-form">
                <%= f.label :month %> <span class="dark mini-text">(MM)</span>
                <%= f.text_field :month, class: "text-field" %>
              </div>
              <div class="one-thirds-form">
                <%= f.label :day %> <span class="dark mini-text">(DD)</span>
                <%= f.text_field :day, class: "text-field" %>
              </div>
              <div class="one-thirds-form">
                <%= f.label :year %> <span class="dark mini-text">(YYYY)</span>
                <%= f.text_field :year, class: "text-field" %>
              </div>
            </div>

            <div class="three-space-bottom-padding center dark">
              None of the information below is saved in Halowake's database. Halowake will not have access to this information after this moment via this website.
            </div>

            <div class="field">
              <%= f.label :line1, "Street address" %>
              <%= f.text_field :line1, required: true, class: "text-field" %>
            </div>
            <div class="flex">
              <div class="one-thirds-form">
                <%= f.label :city %>
                <%= f.text_field :city, required: true, class: "text-field" %>
              </div>
              <div class="one-thirds-form">
                <%= f.label :state %>
                <%= f.text_field :state, required: true, class: "text-field" %>
              </div>
              <div class="one-thirds-form">
                <%= f.label :postal_code %>
                <%= f.text_field :postal_code, required: true, class: "text-field" %>
              </div>
            </div>

          <% if @payment.country == 'US' %>

            <div class="flex">
              <div class="one-half-form">
                <%= f.label :personal_id_number, "Full SS or business tax ID" %>
                <%= f.text_field :personal_id_number, required: true, class: "text-field" %>
              </div>
              <div class="one-half-form">
                <%= f.label :ssn_last_4, "Last 4 of SS" %>
                <%= f.text_field :ssn_last_4, required: true, class: "text-field" %>
              </div>
            </div>

          <% end %>

          <div class="field smedium-text bold center">
            Where will your money go?
          </div>

          <div class="three-space-bottom-padding center dark">
            This is not saved to Halowake's database. Only fill this out if you want to create a new default bank account to transfer funds to.
          </div>

          <% if @payment.country == 'US' %>
            <div class="flex">
              <div class="one-half-form">
                <%= f.label :bank_account_number %>
                <%= f.text_field :bank_account_number, required: true, class: "text-field" %>
              </div>
              <div class="one-half-form">
                <%= f.label :bank_routing_number %>
                <%= f.text_field :bank_routing_number, required: true, class: "text-field" %>
              </div>
            </div>
          <% else %>
            <div class="field">
              <%= f.label :bank_account_number %>
              <%= f.text_field :bank_account_number, required: true, class: "text-field" %>
            </div>
          <% end %>

          <%= f.submit "Update merchant account", data: { disable_with: 'Updating...' }, class: "submit-button" %>

        <% end %>
      </div>
    </div>


  </div>
</div>

app/views/users/payment_settings/new.html.erb
<%= provide(:title, "Set Up A Merchant Account" + " | " + "Halowake") %>

<div class="wrapper">
  <div class="container">

    <div class="three-space medium-text">
      Set up a merchant account
    </div>

    <div class="nameplate border-top">
      <div class="form-container">
        <%= form_for(@payment, url: user_payment_settings_path) do |f| %>
          <%= f.hidden_field :user_id %>
          <%= render 'partials/errors/payment_setting_errors' %>
          
          <div class="flex">
            <div class="one-half-form">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, class: "text-field" %>
            </div>
            <div class="one-half-form">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: "text-field" %>
            </div>
          </div>
          <div class="flex">
            <div class="one-thirds-form">
              <%= f.label :month %> <span class="dark mini-text">(MM)</span>
              <%= f.text_field :month, class: "text-field" %>
            </div>
            <div class="one-thirds-form">
              <%= f.label :day %> <span class="dark mini-text">(DD)</span>
              <%= f.text_field :day, class: "text-field" %>
            </div>
            <div class="one-thirds-form">
              <%= f.label :year %> <span class="dark mini-text">(YYYY)</span>
              <%= f.text_field :year, class: "text-field" %>
            </div>
          </div>

          <div class="field">
            <%= f.label :country %>
            <%= f.select :country, options_for_select(country_select) %>
          </div>

          <div class="three-space-bottom-padding center dark">
            Don't forget that Stripe, our secure payment processor, takes a fee of <i>3% plus 0.30 USD</i> from <i>each transaction</i>. By registering your account, you agree to our <%= link_to 'Terms of Use', terms_path  %> and the <a href="https://stripe.com/connect/account-terms">Stripe Connected Account Agreement</a>.
          </div>

          <%= f.submit "Create merchant account", data: { disable_with: 'Creating...' }, class: "submit-button" %>
        <% end %>
      </div>
    </div>


  </div>
</div>