config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => '/presign'
  end

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms' => 'static_pages#terms'
  get 'about' => 'static_pages#about'

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations",  unlocks: "users/unlocks"}

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
    get 'sign_in', to: 'users/sessions#new'
    get 'register', to: 'users/registrations#new'
    get 'edit_source', to: 'users/registrations#edit_source', path: 'edit_source'
    patch 'update_source', to: 'users/registrations#update_source', path: 'update_source'
  end

  resources :users, path: '', controller: 'users/users', only: :show do
    resource :payment_settings, controller: 'users/payment_settings', only: [:new, :create, :edit, :update]
    resource :profile, controller: 'users/profiles', only: [:edit, :update]
    resource :location, controller: 'users/locations', only: [:edit, :update]
    resource :theme, controller: 'users/themes', only: [:edit, :update]
    resource :membership, controller: 'users/memberships', only: [:new, :create, :edit, :update, :destroy]
    resources :albums, controller: 'users/albums', except: [:index, :new, :edit] do
      resources :photos, controller: 'users/photos', except: [:index, :new, :edit] do
        resources :votes, controller: 'users/votes', only: [:create, :destroy]
        resources :purchases, path: 'purchases', controller: 'users/purchases', only: [:show, :create, :edit, :update, :destroy] do
          member do
            get 'checkout'
            patch 'charge'
          end
        end
      end
    end
    get 'purchases' => 'users/users#purchases'
    get 'votes' => 'users/users#votes'
    get 'following' => 'users/users#following'
    get 'followers' => 'users/users#followers'
  end

  resources :relationships, controller: 'users/relationships', only: [:create, :update, :destroy]

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  
  def create
    user = User.find(params[:followed_id])
    @user = User.friendly.find(user)
    current_user.follow(user)
    respond_to do |format|
      format.html { redirect_to (:back) }
      format.js { render :action => "relationships" }
      flash.now[:notice] = "You have successfully followed #{@user.profile.first_name.presence || @user.username}."
    end
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    @user = User.friendly.find(user)
    current_user.unfollow(user)
    respond_to do |format|
      format.html { redirect_to (:back) }
      format.js { render :action => "relationships" }
      flash.now[:notice] = "You have successfully unfollowed #{@user.profile.first_name.presence || @user.username}."
    end
  end
  
end

app/views/users/partials/relationships/_follow_button.html.erb
<% if user_signed_in? && current_user != @user %>
  <div class="three-space-bottom">
    <% if current_user.following?(@user) %>
      <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
               html: { method: :delete }, remote: true) do |f| %>
        <%= f.submit "Following", class: "submit-button" %>
      <% end %>
    <% else %>
      <%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
        <div><%= hidden_field_tag :followed_id, @user.id %></div>
        <%= f.submit "Follow", class: "submit-button" %>
      <% end %>
    <% end %>
  </div>
<% elsif user_signed_in? == false %>
  <div class="three-space-bottom">
    <%= link_to "Follow", sign_in_path, class: "submit-button" %>
  </div>
<% end %>

app/views/users/partials/relationships/_follower_count.html.erb
<%= link_to pluralize(@user.followers.count, "follower"), user_followers_path(@user) %> 

app/views/users/partials/relationships/_following_count.html.erb
<%= link_to "Following #{@user.following.count}", user_following_path(@user) %>

app/views/users/partials/relationships/_mini_follow_button.html.erb
<% if user_signed_in? && current_user != user %>
  <div>
    <% if current_user.following?(user) %>
      <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
               html: { method: :delete }, remote: true) do |f| %>
        <%= f.submit "Following", class: "mini-following" %>
      <% end %>
    <% else %>
      <%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
        <div><%= hidden_field_tag :followed_id, user.id %></div>
        <%= f.submit "Follow", class: "mini-follow" %>
      <% end %>
    <% end %>
  </div>
<% elsif user_signed_in? == false %>
  <div">
    <%= link_to "Follow", sign_in_path, class: "feed-links" %>
  </div>
<% end %>